cc_binary(
    name = "world",
    srcs = ["world.cpp"],
)

cc_test(
    name = "world_test",
    srcs = ["world_test.cpp"],
    deps = [
        "@googletest//:gmock",
        "@googletest//:gtest_main",
    ],
)
